add Calculator classes and Calculator tests
Ladauser/Calculotor pull request #1
Opened 2021-11-07 12:35 UTC by Ladauser

2021-11-09 16:53 UTC, vchesnakoutest requested changes

2021-11-09 16:53 UTC, vchesnakoutest commented on src/main/java/pages/CalculatorDifferencePage.java
> +    }
все методы калькулятора в принципе можно вынести в один класс. И пакет будет не pages, а просто calculator например

2021-11-09 16:53 UTC, vchesnakoutest commented on src/test/java/tests/CalculatorDifferenceTest.java
> +    public void CalculatorDifferenceCorrectTest(int result, int minusDigit) {
названия методов с маленькой буквы (поправь также в остальных местах)

2021-11-09 16:53 UTC, vchesnakoutest commented on src/test/java/tests/CalculatorDifferenceTest.java
> +    public void CalculatorDifferenceInCorrectNumberTest(int result, int minusDigit) {
сalculatorDifferenceInсorrectNumberTest

2021-11-09 16:53 UTC, vchesnakoutest commented on src/test/java/tests/DataProviderTest.java
> +    @DataProvider(name = "Sum with in correct number values")
incorrect - в одно слово

2021-11-09 16:53 UTC, vchesnakoutest commented on src/test/java/tests/DataProviderTest.java
> +                {1, sum.sum(0, 1)},
sum.sum - действия принято вызывать в самих тестах, в дата провайдере у нас находятся только данные

2021-11-09 16:53 UTC, vchesnakoutest commented on src/test/resources/testng.xml
> +<!--            <parameter name="email" value="test@mailinator.com"></parameter>-->
закоменченный код лучше удалять, если ты его не планируешь использовать

2021-11-10 08:37 UTC, Ladauser commented on src/main/java/pages/CalculatorDifferencePage.java
> +    }
сделала

2021-11-10 08:37 UTC, Ladauser commented on src/test/java/tests/CalculatorDifferenceTest.java
> +    public void CalculatorDifferenceCorrectTest(int result, int minusDigit) {
сделала

2021-11-10 08:37 UTC, Ladauser commented on src/test/java/tests/CalculatorDifferenceTest.java
> +    public void CalculatorDifferenceInCorrectNumberTest(int result, int minusDigit) {
исправила

2021-11-10 08:37 UTC, Ladauser commented on src/test/java/tests/DataProviderTest.java
> +    @DataProvider(name = "Sum with in correct number values")
исправила

2021-11-10 08:37 UTC, Ladauser commented on src/test/java/tests/DataProviderTest.java
> +                {1, sum.sum(0, 1)},
исправила

2021-11-10 08:39 UTC, Ladauser commented on src/test/resources/testng.xml
> +<!--            <parameter name="email" value="test@mailinator.com"></parameter>-->
оставила его для себя, что бы точно не потерять если понадобится такой подход  к  проверкам

2021-11-10 08:39 UTC, merged